### ISSUE TITLE
This is an inquiry - perform assembly loading in mscorlib

### ISSUE THREAD

**Issue by kgorro** [caozhiyuan/ClrProfiler.Trace#1]
1.) Is it possible to apply the same changes for mscorlib?

**Comment by caozhiyuan** [comment]
see this https://github.com/dotnet/coreclr/issues/3894#issuecomment-530041699

**Comment by kgorro** [comment]
@caozhiyuan Based on the link that you have given Assembly.LoadFrom will not suffice but I can use  Assembly ,loadfrom().gettype().getmethod().invoke(), my problem now is the entry point token for mscorlib. Does entry point exist for mscorlib?

**Comment by caozhiyuan** [comment]
@kgorro  entry point is mian method, in iis ,no entry point, in .net framework , Assembly.LoadFrom at entry point  can load dll into appdomain (only way is GAC ).

**Comment by caozhiyuan** [comment]
@kgorro entry point is mian method, in iis ,no entry point, in .net framework , Assembly.LoadFrom at entry point can't load dll into appdomain (only way is GAC ).

**Comment by kgorro** [comment]
@caozhiyuan using Assembly ,loadfrom().gettype().getmethod().invoke() would not also load assembly in appdomains?

**Comment by caozhiyuan** [comment]
yes , it just execute method. in .net framework , can use GAC.

**Comment by kgorro** [comment]
@caozhiyuan what are other alternatives for GAC? especially in azure app services scenario.

**Comment by caozhiyuan** [comment]
in .net framework ,  use GAC  or Assembly ,loadfrom().gettype().getmethod().invoke()  or reference dll

**Comment by kgorro** [comment]
@caozhiyuan i think i would try to Assembly.LoadFrom().gettype().getmethod().invoke(), do you have a sample where I can apply this on mscorlib scenario?

**Comment by caozhiyuan** [comment]
change ilrewrite and make it. i can consult https://github.com/dotnet/coreclr/issues/3894#issuecomment-530041699  david-sackstein

**Comment by caozhiyuan** [comment]
you can  refer to https://github.com/DataDog/dd-trace-dotnet
