### ISSUE TITLE
EntryPointToken for System.Private.Corelib is not working in azure app service

### ISSUE THREAD

**Issue by kgorro** [caozhiyuan/ClrProfiler.Trace#2]
1.) Getting the entry point token for system.private.corlib is not matching with functionToken in jitcompilationstarted.

**Comment by kgorro** [comment]
I got this fix by modifying the signature of loadfrom for 32bit case only. The current code for the signature for loadfrom does not work for x86.

**Comment by caozhiyuan** [comment]
entry point token is function token  of main method, system.private.corlib seems have not entry point token . @kgorro

**Comment by kgorro** [comment]
> entry point token is function token of main method, system.private.corlib seems have not entry point token . @kgorro

Wrong title of the issue, it is the signature of load from that is wrong in x86 runtime. I think the code is correct but somehow the generation of the signature for loadfrom is erroneous. I revise how signature of loadfrom was generated.

**Comment by caozhiyuan** [comment]
yes if .net framework x86 something need ajust. refer to this :https://github.com/jimschubert/clr-profiler

**Comment by caozhiyuan** [comment]
https://github.com/jimschubert/clr-profiler/tree/master/src/ILRewrite10Source @kgorro

**Comment by kgorro** [comment]
@caozhiyuan thanks for this but I have already a fix for this. I am not sure why dynamic allocation in the heap will not work, i created an array with 8 elements and then get size of the integer and the compress token of system.loadfrom and I revise how to compute the size of the signature and it is working now.

**Comment by caozhiyuan** [comment]
refer to this https://github.com/caozhiyuan/ClrProfiler.Trace/blob/master/src/ClrProfiler/CorProfiler.cpp#L429 @kgorro

**Comment by caozhiyuan** [comment]
helper link to understand method sig https://www.codeproject.com/Articles/42655/NET-file-format-Signatures-under-the-hood-Part-2#LocalVarSig1.1

**Comment by kgorro** [comment]
@caozhiyuan thank you for this, I have a question, for .NET framework, is there an entry point method? or what method do you suggest for me to inject a call to system.reflection.assembly.load(). because what I am trying is to reference my C# dll on the application being profiled.

**Comment by caozhiyuan** [comment]
.net framework use GAC

**Comment by kgorro** [comment]
@caozhiyuan , we already use that and it is working. What I am trying to is for azure app service for dotnet framework and We are trying to reference the C# dll that we want to call in our instrumentation but it has still problems even if we reference it.

**Comment by caozhiyuan** [comment]
any error ? you can use native debug.

**Comment by kgorro** [comment]
The c# dll is loaded late and sometimes it is not (no module load) even though it was reference already.
