### ISSUE TITLE
iis 下加载探查器失败

### ISSUE THREAD

**Issue by tcsecchen** [caozhiyuan/ClrProfiler.Trace#3]
我想对部署在iis上的应用进行分析，但。。加载探查器时失败（没有日志文件产生）
![图片](https://user-images.githubusercontent.com/25191604/75568753-d2665880-5a8e-11ea-9d07-d3fbc36b1b1c.png)
并非.net版本问题，不在iis上的应用程序使用相同版本.net可以正常加载探查器而且日志正常
![图片](https://user-images.githubusercontent.com/25191604/75568897-148f9a00-5a8f-11ea-9908-65f50225cd10.png)

也不是权限的问题，我给dll分配了everyone所有权限

emmm，所以，您遇到过这种情况吗，希望的到帮助，谢谢！！

i think you are Chinese，so i use Chinese，i can use English also

thanks

**Comment by caozhiyuan** [comment]
.net 版本多少？

**Comment by tcsecchen** [comment]
事件日志上显示是4.0.30319,
C:\Windows\Microsoft.NET\Framework64\v4.0.30319 (framework目录也是这个版本）
但是我本机有.net4.8
![图片](https://user-images.githubusercontent.com/25191604/75600917-79c7a780-5af0-11ea-8787-03482d4bb50c.png)

不在iis的应用程序和iis的  事件日志中显示的 .net Runtime version是一样的

**Comment by caozhiyuan** [comment]
.net4.8 ? maybe c++ profiler coreclr header need update ,  you can try net471?

**Comment by caozhiyuan** [comment]
net471 can work? @tcsecchen

**Comment by tcsecchen** [comment]
> 
> 
> net471 can work? @tcsecchen

不好意思，前两天有点忙，今天我试一下net471

**Comment by tcsecchen** [comment]
嘿，我试过了，还是相同的报错
我新装了win server 2016，它自带.net 461，也会报一开始图片中的那个错误
后来我升级到4.7.1，也不行

比较奇怪的点是，桌面程序或者其他windows的一些自带程序是可以加载的，只有iis 下w3wp.exe这个加载会出现这个问题。。。

**Comment by tcsecchen** [comment]
https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI/ReJITEnterLeaveHooks
这个项目的CorProfiler.dll是可以在iis被加载的，.net4.8
![图片](https://user-images.githubusercontent.com/25191604/75694579-b4ddfc80-5ce3-11ea-99c7-59dc3f1305cc.png)

**Comment by caozhiyuan** [comment]
use this https://github.com/caozhiyuan/SkyAPM-dotnet/releases/tag/CI   SkyApm.DotNet.Installer.msi , i test ok on iis net471 .

**Comment by tcsecchen** [comment]
i'm sorry，我试过了.net 4.8 iis环境下此项目也是可以的，上述问题的真正原因：src\ClrProfiler.Trace\bin\Debug\net461 目录iis的应用程序池没有访问权限（没错，坑爹的原因坑爹的报错）

总结一下问题表现：
iisreset后访问网站，此时iis会启动一个w3wp.exe，windows事件查看器会显示最上面评论图一的报错，而且net461/logs目录下没有对应pid的日志文件

排查可以使用[Process Monitor](https://docs.microsoft.com/zh-cn/sysinternals/downloads/procmon)
![图片](https://user-images.githubusercontent.com/25191604/75766954-e9ea5d80-5d7c-11ea-88f2-764bb530ec7a.png)
可以清楚看到报错详情（吊打事件查看器）

解决方案建议按readme中标准流程使用msi安装包进行安装，自己直接编译要把net461整个目录分配iis 对应apppool读取以及写入的权限（简单点的话可以配置Everyone所有权限）

ok，目前iis可以正常加载ClrProfiler了，完结撒花

感谢项目作者的支持，tks
