### ISSUE TITLE
I want to Instrumentation the System.String.Concat method

### ISSUE THREAD

**Issue by jiaxiang8756** [caozhiyuan/ClrProfiler.Trace#5]
Hello, I have a problem. I want to Instrumentation the System.String.Concat method, but I see you have such code in the JitCompilationStarted method in corprofiler.cpp：

```C++
 if (!(functionInfo.signature.CallingConvention() & IMAGE_CEE_CS_CALLCONV_HASTHIS)) {

	return S_OK;

}
```
System.string.concat has been filtered out. What is the purpose of this？

**Comment by jiaxiang8756** [comment]
我去，看了下作者，是国内大哥，我在这重发下:我想给System.string.concat这个方法插桩，但是我看你代码里面：
```C++
 if (!(functionInfo.signature.CallingConvention() & IMAGE_CEE_CS_CALLCONV_HASTHIS)) {

	return S_OK;

}
```
这几句代码给过滤掉了，这个过滤的目的是什么呢。我如何给concat插桩呢？

**Comment by budcaozhiyuan** [comment]
> 我去，看了下作者，是国内大哥，我在这重发下:我想给System.string.concat这个方法插桩，但是我看你代码里面：
> 
> ```c++
>  if (!(functionInfo.signature.CallingConvention() & IMAGE_CEE_CS_CALLCONV_HASTHIS)) {
> 
> 	return S_OK;
> 
> }
> ```
> 
> 这几句代码给过滤掉了，这个过滤的目的是什么呢。我如何给concat插桩呢？

目前只支持实例方法  不支持static方法 你可以看下ilrewrite逻辑

**Comment by budcaozhiyuan** [comment]
https://www.cnblogs.com/caozhiyuan/p/10352650.html
