### ISSUE TITLE
32bit

### ISSUE THREAD

**Issue by yanggr** [caozhiyuan/ClrProfiler.Trace#6]
大佬，请教下，目前支持32位的网站吗？

**Comment by yanggr** [comment]
在IIS程序池【启用32位程序模式】设置为true时，就是出现【错误的二进制签名】异常，请教下大佬，目前有可解决方案或者参考文献，来解决32位站点的兼容性问题吗？

**Comment by caozhiyuan** [comment]
需要把ClrProfiler打包成x86 @yanggr  https://github.com/caozhiyuan/ClrProfiler.Trace/tree/master/src/ClrProfiler  很长时间没搞这个了  你研究下

**Comment by caozhiyuan** [comment]
最简单就是用64位运行程序
